import * as core from '@actions/core'
import * as github from '@actions/github'
import * as exec from '@actions/exec'
import * as fs from 'fs'
import * as path from 'path'

export interface GeneratedDoc {
  sourceFile: string
  docFile: string
  content: string
  isNew: boolean
}

// ─────────────────────────────────────────────
// DOC FILE PATH
// ─────────────────────────────────────────────

export function getDocFilePath(
  sourceFile: string,
  docsPath: string,
  style: string
): string {
  const ext = style === 'rst' ? '.rst' : '.md'
  // Flatten path — src/auth/service.ts → docs/src-auth-service.md
  const flat = sourceFile
    .replace(/\//g, '-')
    .replace(/\.[^.]+$/, '') // remove extension
  return path.join(docsPath, `${flat}${ext}`)
}

// ─────────────────────────────────────────────
// FORMAT DOC CONTENT
// ─────────────────────────────────────────────

export function formatDocContent(
  rawContent: string,
  sourceFile: string,
  style: string,
  provider: string
): string {
  const now = new Date().toISOString().split('T')[0]
  const providerLabel = {
    'github-models': 'GitHub Models (gpt-4o-mini)',
    'openai': 'OpenAI (gpt-4o-mini)',
    'anthropic': 'Anthropic (Claude Haiku)'
  }[provider] || provider

  if (style === 'rst') {
    return `.. _${sourceFile.replace(/[^a-zA-Z0-9]/g, '_')}:

${rawContent}

----

.. note::
   Auto-generated by \`AutoDocs <https://github.com/marketplace/actions/autodocs>\`_ using ${providerLabel} on ${now}.
   Source: \`\`${sourceFile}\`\`
`
  }

  return `${rawContent}

---

> 📝 Auto-generated by [AutoDocs](https://github.com/marketplace/actions/autodocs) using ${providerLabel} on ${now}
> Source: \`${sourceFile}\`
`
}

// ─────────────────────────────────────────────
// COMMIT DOCS
// ─────────────────────────────────────────────

export async function commitDocs(
  docs: GeneratedDoc[],
  branch: string,
  message: string
): Promise<boolean> {
  try {
    // Configure git
    await exec.exec('git', ['config', 'user.name', 'autodocs[bot]'])
    await exec.exec('git', ['config', 'user.email', 'autodocs[bot]@users.noreply.github.com'])

    // Write all doc files
    for (const doc of docs) {
      const dir = path.dirname(doc.docFile)
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true })
      }
      fs.writeFileSync(doc.docFile, doc.content, 'utf-8')
      core.info(`📝 Written: ${doc.docFile}`)
    }

    // Stage all doc files
    const docFiles = docs.map(d => d.docFile)
    await exec.exec('git', ['add', ...docFiles])

    // Check if there's anything to commit
    let hasChanges = false
    await exec.exec('git', ['diff', '--staged', '--quiet'], {
      ignoreReturnCode: true,
      listeners: {
        stderr: () => { hasChanges = true }
      }
    })

    // Use exit code to detect changes
    const result = await exec.exec('git', ['diff', '--staged', '--name-only'], {
      ignoreReturnCode: true
    })

    if (result === 0) {
      // Double check with status
      let output = ''
      await exec.exec('git', ['status', '--porcelain'], {
        listeners: { stdout: (data) => { output += data.toString() } }
      })
      if (!output.trim()) {
        core.info('ℹ️ No doc changes to commit')
        return false
      }
    }

    await exec.exec('git', ['commit', '-m', `${message} [skip ci]`])
    await exec.exec('git', ['push', 'origin', branch])

    core.info(`✅ Docs committed and pushed to ${branch}`)
    return true
  } catch (err) {
    core.warning(`⚠️ Failed to commit docs: ${err}`)
    return false
  }
}

// ─────────────────────────────────────────────
// CREATE PR
// ─────────────────────────────────────────────

export async function createDocsPR(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  docs: GeneratedDoc[],
  baseBranch: string,
  commitMessage: string
): Promise<string | null> {
  try {
    const docsBranch = `autodocs/${baseBranch}-${Date.now()}`

    // Create new branch
    const { data: baseRef } = await octokit.rest.git.getRef({
      owner, repo, ref: `heads/${baseBranch}`
    })

    await octokit.rest.git.createRef({
      owner, repo,
      ref: `refs/heads/${docsBranch}`,
      sha: baseRef.object.sha
    })

    // Commit each doc file to the new branch
    for (const doc of docs) {
      const content = Buffer.from(doc.content).toString('base64')

      try {
        // Check if file exists
        const { data: existing } = await octokit.rest.repos.getContent({
          owner, repo, path: doc.docFile, ref: docsBranch
        })
        const sha = 'sha' in existing ? existing.sha : undefined

        await octokit.rest.repos.createOrUpdateFileContents({
          owner, repo,
          path: doc.docFile,
          message: `docs: update ${doc.docFile} [skip ci]`,
          content,
          sha,
          branch: docsBranch
        })
      } catch {
        // File doesn't exist — create it
        await octokit.rest.repos.createOrUpdateFileContents({
          owner, repo,
          path: doc.docFile,
          message: `docs: add ${doc.docFile} [skip ci]`,
          content,
          branch: docsBranch
        })
      }
    }

    // Create PR
    const newDocs = docs.filter(d => d.isNew).length
    const updatedDocs = docs.filter(d => !d.isNew).length

    const body = `## 📝 AutoDocs — Generated Documentation

This PR was automatically created by [AutoDocs](https://github.com/marketplace/actions/autodocs).

### Summary
- 📄 **${newDocs}** new documentation files
- 🔄 **${updatedDocs}** updated documentation files
- 📁 Documentation path: \`${docs[0]?.docFile.split('/')[0] || 'docs'}/\`

### Files Documented
${docs.map(d => `- \`${d.sourceFile}\` → \`${d.docFile}\``).join('\n')}

---
> Review and merge when ready. Edit any generated docs before merging if needed.`

    const { data: pr } = await octokit.rest.pulls.create({
      owner, repo,
      title: `📝 AutoDocs: Generated documentation for ${docs.length} file${docs.length !== 1 ? 's' : ''}`,
      head: docsBranch,
      base: baseBranch,
      body
    })

    core.info(`✅ Created docs PR: ${pr.html_url}`)
    return pr.html_url
  } catch (err) {
    core.warning(`⚠️ Failed to create docs PR: ${err}`)
    return null
  }
}

// ─────────────────────────────────────────────
// PR COMMENT
// ─────────────────────────────────────────────

export async function postPRComment(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
  docs: GeneratedDoc[],
  prUrl: string | null,
  autoCommitted: boolean,
  provider: string
): Promise<void> {
  const newDocs = docs.filter(d => d.isNew).length
  const updatedDocs = docs.filter(d => !d.isNew).length

  const deliveryNote = prUrl
    ? `📬 Docs delivered in a [separate PR](${prUrl})`
    : autoCommitted
      ? `✅ Docs committed directly to this branch`
      : `⚠️ Docs were generated but not committed (auto-commit is disabled)`

  const body = `## 📝 AutoDocs — Documentation Generated

${deliveryNote}

| | |
|---|---|
| **New docs** | ${newDocs} file${newDocs !== 1 ? 's' : ''} |
| **Updated docs** | ${updatedDocs} file${updatedDocs !== 1 ? 's' : ''} |
| **AI provider** | ${provider} |

### Files Documented
${docs.map(d => `- \`${d.sourceFile}\` → \`${d.docFile}\``).join('\n')}

---
<sub>📝 Generated by [AutoDocs](https://github.com/marketplace/actions/autodocs)</sub>`

  try {
    // Check for existing AutoDocs comment
    const { data: comments } = await octokit.rest.issues.listComments({
      owner, repo, issue_number: prNumber
    })

    const existing = comments.find(c => c.body?.includes('AutoDocs — Documentation Generated'))

    if (existing) {
      await octokit.rest.issues.updateComment({
        owner, repo, comment_id: existing.id, body
      })
    } else {
      await octokit.rest.issues.createComment({
        owner, repo, issue_number: prNumber, body
      })
    }
  } catch (err) {
    core.warning(`⚠️ Failed to post PR comment: ${err}`)
  }
}
